server:
  port: 8085

spring:
  rabbitmq:
    port: 5672
    host: 127.0.0.1
    username: guest
    password: guest
    publisher-confirms: true
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual #采用手动应答